### ISSUE TITLE
Switch to search-index version 0.9.1

### ISSUE THREAD

**Issue by eklem** [eklem/norch-vuejs-app#21]
When search-index is mature enough

**Comment by eklem** [comment]
Meaning: When norch v.0.8.x is out. And that's now: https://github.com/fergiemcdowall/norch/pull/122

**Comment by eklem** [comment]
Categories (showing) and filtering on categories are the two main issues here.

**Comment by eklem** [comment]
Got a JSON query working towards the norch server:
http://oppskrift.klemespen.com:3030/search?q={%22query%22:{%22AND%22:{%22Varenavn%22:[%22champagne%22]}}}

**Comment by fergiemcdowall** [comment]
Sweet! :)

**Comment by eklem** [comment]
Here is categories:
http://oppskrift.klemespen.com:3030/categorize?q={%22query%22:[{%22AND%22:{%22*%22:[%22*%22]}}],%22category%22:{%22field%22:%22Land%22}}

... and buckets
http://oppskrift.klemespen.com:3030/buckets?q={%22query%22:[{%22AND%22:{%22*%22:[%22*%22]}}],%22buckets%22:[{%22field%22:%22Volum%22,%22gte%22:%220%22,%22lte%22:%220.75%22,%22set%22:false},{%22field%22:%22Volum%22,%22gte%22:%220.76%22,%22lte%22:%2215%22,%22set%22:false}]}

**Comment by eklem** [comment]
It's working! Now I just have to get enough of norch-functionality into the project
