### ISSUE TITLE
Test cutestrap for css

### ISSUE THREAD

**Issue by eklem** [eklem/norch-vuejs-app#8]
Part of the idea with `norch-vuejs-app` is to browserify it. Then we need to keep the amount of code down. The other part is that it should be easy to hack. Maybe [cutestrap](https://github.com/cutestrap/cutestrap) will fit nicely?

**Comment by fergiemcdowall** [comment]
Bootstrap is definitely a bit of a monster.

**Comment by eklem** [comment]
I was thinking about coding all the css myself,  but some support would
save me a lot of time, better used elsewhere.  And 8 kb is not bad.
23. mai 2016 11.13 a.m. skrev "Fergus McDowall" notifications@github.com:

**Comment by eklem** [comment]
Seems a bit limiting. Too much I have to build myself. Maybe [vue-strap](http://yuche.github.io/vue-strap/) could work? Still bootstrap, but will be able to get ridd of jquery.

Has a pretty nice [typeahead-example](http://yuche.github.io/vue-strap/#typeahead) that would fit the [matcher](https://github.com/fergiemcdowall/search-index/blob/master/doc/autosuggest.md) well.

If I use some bootstrap stuff, I'll have to strip it to only include the css that I actually use.

**Comment by eklem** [comment]
Tested. A bit limiting. Will switch to something else later, but stays for now.
